name: Stable Branch Workflow
on:
  push:
    branches:
      - stable
      - stage

jobs:
  stage-deployment:
    name: Trigger a new stage deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'
    steps:
      - name: Create new Gitlab pipeline for Shopware 5
        run: |
          curl -XPOST -H "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" "https://gitlab.marmalade.de/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/pipeline?ref=${{ secrets.GITLAB_SHOPWARE_REF }}"
  release:
    name: Create a new release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stable'
    steps:
      - name: Clone code repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install npm dependencies
        run: yarn

      - name: Semantic release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

          GIT_AUTHOR_NAME: ${{ secrets.GIT_USERNAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_USERNAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}

  swpackage:
    needs: release
    name: Create a new package for shopware
    runs-on: ubuntu-latest    
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: 7.4           

      - name: Checkout github repo
        uses: actions/checkout@v2
        with:
          path: MakairaConnect

      - name: Checkout code repo  
        working-directory: ./MakairaConnect
        run: git checkout

      - name: Copy .git
        run: cp -r  ./MakairaConnect/.git .
          
      - uses: actions-ecosystem/action-get-latest-tag@v1                
        id: get-latest-tag
        
      - name: Install Dependencies
        working-directory: ./MakairaConnect
        run: |
          sed -i '/shopware\/shopware/d' composer.json >> composer.json
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist  
        
      - name: Remove build files
        working-directory: ./MakairaConnect
        run: |  
          rm -rf .github/workflows 
          rm -rf .git
          rm .gitignore
          rm .releaserc.json
          rm composer.json
          rm package.json
          rm yarn.lock
          rm composer.lock

      - name: Zip artifact for deployment        
        run: zip ${{ steps.get-latest-tag.outputs.tag }}.zip ./MakairaConnect/* -r
 
      - name: 'Upload package'
        uses: 'actions/upload-artifact@v2'
        with:
          name: ${{ steps.get-latest-tag.outputs.tag }}
          path: ${{ steps.get-latest-tag.outputs.tag }}.zip
